version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: libraryt-nginx
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./project:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    restart: always
  php:
    build:
      dockerfile: Dockerfile
      context: 'docker'
      args:
        PHP_USER_ID: 1000
        PHP_USER_NAME: libraryt-auto
    container_name: libraryt-php
    env_file:
      - .env
    volumes:
      - ./project:/app
    restart: always
  db:
    image: mariadb:10.11
    container_name: libraryt-mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data/:/var/lib/mysql:rw
      - ./mysql_dump/:/mysql_dump/:rw
    restart: always
  adminer:
    image: adminer
    container_name: libraryt-adminer
    restart: always
    ports:
      - "127.0.0.1:8281:8080"
volumes:
  mysql-data:
